include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    prefer_const_declarations: true
    avoid_print: true
    avoid_web_libraries_in_flutter: true